config/routes.rb
Rails.application.routes.draw do
  resources :pets do
    resources :adoptions
  end
  root 'pets#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adoption.rb
class Adoption < ApplicationRecord
    belongs_to :pet
    validates :name, :date, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet <ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    has_one_attached :avatar
    has_one :adoption
    
    validates :name, :pet_type, :avatar, presence: true
    
    enum pet_type: { dog: 'dog', cat: 'cat', other: 'other' } 
end

app/controllers/adoptions_controller.rb
class AdoptionsController < ApplicationController

    before_action :pet, only: [:create]

    def new
        @adoption = Adoption.new
    end
    
    def create
        @adoption = Adoption.new(adoption_params.merge(date: Date.today, pet: @pet))
      
        if @adoption.save

            flash[:success] = "Prabens #{@adoption.name}, seu novo amigo(a) #{@pet.name} agradece de coração..."
            redirect_to pets_path
        else
            
            flash[:error] = "Novo Dono Não foi Criado..."
            render :new
        end
         
    end
    
    private

    def adoption_params
        params.require(:adoption).permit(:name)
    end

    def pet
        @pet = Pet.friendly.find(params[:pet_id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    def index 
        @pets = Pet.all
    end
    
    def new
        @pet = Pet.new
    end
    
    def edit
        @pet = Pet.find(params[:id])
    end

    def show
        @pet = Pet.friendly.find(params[:id])
        if @pet.nil?
            redirect_to  action: :index
        end
    end

    def update
        @pet = Pet.find(params[:id])
        if @pet.update(pet_params)
            flash[:success] = "Pet Atualizado Com Sucesso..."
            redirect_to(@pet)
        else
            flash[:error] = "Seu Pet Não foi Atualizado..."
            render :edit
        end
    end


    def create
        @pet = Pet.new(pet_params)
        
        if @pet.save
            flash[:success] = "Pet Criado Com Sucesso..."
            redirect_to pets_path
        else
            puts @pet.errors.inspect
            flash[:error] = "Pet Não foi Criado..."
            render :new
        end    
    end
    
    private

    def pet_params
        params.require(:pet).permit(:name, :date_of_birth, :pet_type, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def flash_class(level)
        case level
            when :notice then 'alert alert-info'
            when :success then 'alert alert-success'
            when :error then 'alert alert-danger'
            when :alert then 'alert alert-warning'
        end
    end
end

app/views/adoptions/_form.html.erb
<%= bootstrap_form_for adoption, url: pet_adoptions_path do |f| %>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <%= f.text_field :name, required: true %>
    </div>
</div>

<div class="row">
    <div class="col-md-1 offset-md-9">
        <%= f.submit "Create", class: "btn btn-default btn-primary" %>
    </div>
</div>

<% end %>

app/views/adoptions/new.html.erb
<div class="col-md-8 offset-md-2">
    <h1>Nova Adoção</h1>
</div>
<%flash.each do |key, value|%>

<%end%>
<%= render partial: "form", locals: {adoption: @adoption} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>PetAdoption</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%flash.each do |key, value|%>
  <div class='<%= flash_class(key.to_sym) %>'>
    <%= value %>
  </div>
  <% end %>
  <%= yield %>
</body>

</html>

app/views/pets/_form.html.erb
<%= bootstrap_form_for(pet) do |f| %>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <%= f.text_field :name, required: true %>
    </div>
</div>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <%= f.file_field :avatar %>
    </div>
</div>
<div class="row">
    <div class="col-md-8 offset-md-2">
        <%= f.date_field :date_of_birth, required: true %>
    </div>
</div>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <%= f.select(:pet_type, [['Gato', :cat], ['Cachorro', :dog], ['Outros', :other]], { include_blank: 'Selecione uma opção' }, required: true ) %>
    </div>
</div>

<div class="row">
    <div class="col-md-1 offset-md-7">
        <%= f.submit btn_label, class: "btn btn-default btn-primary" %>
    </div>
    <div class="col-md-1 offset-md-1">
        <%= link_to 'Voltar', pets_path, class: "btn btn-default btn-primary" %>
    </div>
</div>

<% end %>

app/views/pets/edit.html.erb
<div class="col-md-8 offset-md-2">
    <h1>Editar Pet</h1>
</div>
<%= render partial: "form", locals: {pet: @pet, btn_label: 'Update'} %>

app/views/pets/index.html.erb
<div class="container">
    <div class="card m-5">
        <div class="card-header">
            <div class="row">
                <div class="col-md-12">
                    <div class="header">
                        <div class="float-center">
                            <h4 class="header-title">Pets</h4>
                        </div>
                        <div>
                            <div class="custom-control custom-radio">
                                <input type="radio" id="customRadio1" name="customRadio" data-type="not_adopted"
                                    class="custom-control-input">
                                <label class="custom-control-label" for="customRadio1">Pets Disponíveis</label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input type="radio" id="customRadio2" name="customRadio" data-type="adopted"
                                    class="custom-control-input">
                                <label class="custom-control-label" for="customRadio2">Pets Adotados</label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input checked type="radio" id="customRadio3" name="customRadio" data-type="all"
                                    class="custom-control-input">
                                <label class="custom-control-label" for="customRadio3">Todos</label>
                            </div>
                        </div>
                        <div class="float-right">
                            <%= link_to "Novo Pet", new_pet_path, class: 'btn btn-sm btn-success' %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body" data-teste="div_all" id="all">
            <% if @pets.any? %>
            <div class="table-responsive">
                <table class='table'>
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Nascimento</th>
                            <th>Tipo</th>
                            <th>Adotar</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%@pets.each do |pet|%>
                        <tr>
                            <td><%= pet.name %></td>
                            <td><%= pet.date_of_birth.strftime('%d/%m/%Y') %></td>
                            <td><%= pet.pet_type %></td>
                            <% if pet.adoption %>
                            <td>Adotado por <%= pet.adoption.name %></td>
                            <% else %>
                            <td><%= link_to "Adotar", new_pet_adoption_path(pet), class: 'btn btn-sm btn-info' %>
                            </td>
                            <% end %>
                            <td>
                                <%= link_to edit_pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-edit"></i>
                                <% end %>
                                <%= link_to pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-eye"></i>
                                <% end %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <%else%>
            <div class="text-center">
                Nenhum Pet Cadastrado
            </div>
            <%end%>
        </div>
        <div class="card-body d-none" data-teste="div_adopted" id="adopted">
            <% if @pets.any? %>
            <div class="table-responsive">
                <table class='table'>
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Nascimento</th>
                            <th>Tipo</th>
                            <th>Adotar</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @pets.select{ |pet| pet.adoption }.each do |pet| %>
                        <tr>
                            <td><%= pet.name %></td>
                            <td><%= pet.date_of_birth.strftime('%d/%m/%Y') %></td>
                            <td><%= pet.pet_type %></td>
                            <% if pet.adoption %>
                            <td>Adotado por <%= pet.adoption.name %></td>
                            <% else %>
                            <td><%= link_to "Adotar", new_pet_adoption_path(pet), class: 'btn btn-sm btn-info' %>
                            </td>
                            <% end %>
                            <td>
                                <%= link_to edit_pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-edit"></i>
                                <% end %>
                                <%= link_to pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-eye"></i>
                                <% end %>
                            </td>

                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <%else%>
            <div class="text-center">
                Nenhum Pet Cadastrado
            </div>
            <%end%>
        </div>

        <div class="card-body d-none" data-teste="div_not_adopted" id="not_adopted">
            <% if @pets.any? %>
            <div class="table-responsive">
                <table class='table'>
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Nascimento</th>
                            <th>Tipo</th>
                            <th>Adotar</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <%@pets.select{|pet| pet.adoption.nil?}.each do |pet|%>
                        <tr>
                            <td><%= pet.name %></td>
                            <td><%= pet.date_of_birth.strftime('%d/%m/%Y') %></td>
                            <td><%= pet.pet_type %></td>
                            <% if pet.adoption %>
                            <td>Pet Adotado</td>
                            <% else %>
                            <td><%= link_to "Adotar", new_pet_adoption_path(pet), class: 'btn btn-sm btn-info' %>
                            </td>
                            <% end %>
                            <td>
                                <%= link_to edit_pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-edit"></i>
                                <% end %>
                                <%= link_to pet_path(pet), class: 'btn btn-sm btn-info' do %>
                                <i class="fa fa-eye"></i>
                                <% end %>
                            </td>

                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <%else%>
            <div class="text-center">
                Nenhum Pet Cadastrado
            </div>
            <%end%>
        </div>

    </div>
</div>
<script>
    $(function () {
        $('input[name=customRadio]').on('change', function () {
            radio = $(this);
            radioType = radio.data('type')
            cardBody = document.getElementById(radioType)
            $('.card-body').addClass('d-none')
            $(cardBody).removeClass('d-none')
        })
    });
</script>

app/views/pets/new.html.erb
<div class="col-md-8 offset-md-5">
    <h1>Novo Pet</h1>
</div>
<%= render partial: "form", locals: {pet: @pet, btn_label: 'Cadastrar Pet'} %>

app/views/pets/show.html.erb
<div class="card container">
    <div class="card-body">
        <h5 class="card-title"><%= @pet.name.upcase %></h5>
        <div class="row">
            <div class="col-md-4">
                <%= image_tag @pet.avatar %>
            </div>
            <div class="col-md-6">
                <strong>
                    <p class="card-text">Nome:
                </strong> <%= @pet.name.upcase %>
                </p>
                </row>
                <row>
                    <strong>
                        <p class="card-text">Nascimento:
                    </strong> <%= @pet.date_of_birth.strftime('%d/%m/%Y') %>
                    </p>
                </row>
                <row>
                    <strong>
                        <p class="card-text">Tipo do Pet:
                    </strong> <%= @pet.pet_type %>
                    </p>
                </row>
                <row>
                    <strong>
                        <p class="card-text">Novo(a) Pai/Mãe:
                    </strong> <%= @pet.adoption.name %>
                    </p>
                </row>
            </div>
        </div>

        <row>
            <strong>
            </strong>
            </p>
        </row>
        <a><%= link_to 'Editar', edit_pet_path(@pet), class: "btn btn-default btn-primary" %></a>
        <a><%= link_to 'Voltar', pets_path, class: "btn btn-default btn-primary" %></a>
        </p>
    </div>
</div>